apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
  labels:
    app: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - name: books
        image: 427835582574.dkr.ecr.us-east-1.amazonaws.com/shopping-site-books:ce2fc09c61ae3c042e415d4319697bf043d1248f
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books
spec:
  type: ClusterIP
  selector:
    app: books
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
